### ISSUE TITLE
Ideas for stickers

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/design#4]
Putting here ideas we've had about stickers, such as:
- having one year-specific sticker design and a general one
- using our #rgsoc hashtag
- a heart-shaped sticker

**Comment by sareg0** [comment]
oooh schweeet!
Can we attach the file for the stickers you had printed in a folder on the repo? Just in case we'd like some more printed. Actually I will just make a directory :D

**Comment by alicetragedy** [comment]
@sareg0 added!

**Comment by sareg0** [comment]
awesome! Well we have that first design. Are you happy to get more of those printed? We may do a stickermule order quite soon. Did we want to do a few more of the proposed designs before we do the SM order? So we have a few types, and can do a large print.

**Comment by alicetragedy** [comment]
@sareg0 maybe we can set a deadline by when we want to place the order, and I can see if I come up with more designs by then? I could try to put something together this/next week.

**Comment by sareg0** [comment]
Shall we say we'll order on Friday 27th March. If you don't have the time it's allll good. Just if there is time is all

**Comment by alicetragedy** [comment]
That sounds like a good plan to me @sareg0. Or maybe we could move the deadline to March 30th? (that would give me an extra weekend, and anyway if there are things to be changed in the original file, it's probably better to do it at the beginning of the week, so we have support if needed).

I'd love to get some die-cut stickers! They're awesome..

**Comment by sareg0** [comment]
yeah, good idea, and some breathing room for you too. Yeah I would really love die-cut stickers. They are so super nice. Okay, so let's say, about March 30th we'll do an order, and see how far we get. Do you think @apertoclaudi would like to help? Is that the sort of designer that she is?

**Comment by ApertoClaudi** [comment]
Yeah, I would really like to help! I'm just moving and have to pack some things this week but I think next week I can make some designs.

**Comment by sareg0** [comment]
awesome!! Perhaps you and @alicetragedy could do some back and forth on it, and come up with some amazeballs designs, for potentially amazeballs stickers

**Comment by alicetragedy** [comment]
:+1: totally!

**Comment by ApertoClaudi** [comment]
Yeah, @alicetragedy and me are the amazeballs-sticker-team! 

![bbb](https://cloud.githubusercontent.com/assets/7582849/6713005/0b2811ae-cd90-11e4-9cfe-df91ff3c8055.gif)

**Comment by sareg0** [comment]
I'm sorry but where did that gif come from it's blowing my mind :D

**Comment by ApertoClaudi** [comment]
Haha, it comes from here: https://www.youtube.com/watch?v=ovqM72em1dA So hilarious! ^^

**Comment by alicetragedy** [comment]
could we have a little bit more time for the sticker-ordering? (eg. maybe Easter Monday or this weekend) I'm on holiday from Wednesday, and maybe also @ApertoClaudi will have more time this week. It would be great to design a special edition of the stickers for all the people who have donated <3

**Comment by sareg0** [comment]
yes! I understand, it hasn't taken much presedence in amongst everything else... All in all I'm happy if we can order them so they can be put in the swag packs, so I don't mind too much :)

**Comment by sareg0** [comment]
I just came across the ruby together stickers! <3 
https://twitter.com/rubytogether/status/583594199951527936

**Comment by ApertoClaudi** [comment]
So, finally I made some sticker layouts. I tried different shapes, so your feedback please. :smile_cat: 
![rgsoc-sticker-mockup](https://cloud.githubusercontent.com/assets/7582849/7870288/93886a8c-0588-11e5-814e-06507d76e7dc.jpg)
![rgsoc-sticker-01](https://cloud.githubusercontent.com/assets/7582849/7870299/a0b82882-0588-11e5-9df9-11a464b05a25.png)
![rgsoc-sticker-02](https://cloud.githubusercontent.com/assets/7582849/7870301/a0bb0e76-0588-11e5-8afd-5e1733ccdaff.png)
![rgsoc-sticker-03](https://cloud.githubusercontent.com/assets/7582849/7870298/a0b6b056-0588-11e5-8853-a8460de44bad.png)
![rgsoc-sticker-04](https://cloud.githubusercontent.com/assets/7582849/7870300/a0b99dac-0588-11e5-801f-6a62f25932b8.png)

**Comment by katrin-k** [comment]
can i preorder a few of the megaphones, plz. <3

**Comment by sareg0** [comment]
I particularly like the megaphone :)

**Comment by alicetragedy** [comment]
I like the megaphone too! and the small hearts look great. :heart_eyes: 
I think the big profiled heart would look good too, but without "Berlin" and with "Rails Girls Summer of Code" (or RGSoC) instead. Not sure if there is enough space, though.

I just have one comment regarding the typeface – it would be great if we could use the one that's on the website, @ApertoClaudi I will send you a mail later about it :)

**Comment by ApertoClaudi** [comment]
Thanx for all your feedback! <3 The megaphone one is also my favourite! ^^ 
@bioshrimp: Do you have the megaphone as a vector file? That would be better, if we want to print those stickers. :)

@alicetragedy I actually used the Lato font for the sticker. :) And I changed it now to RGSoC, because the other version ist definitely too long. ( @anikalindtner tl;dr ;) )
But what kind of red did you use for your sticker? I just can find the HEX or RGB but no information about CMYK vaues. 

![rgsoc-sticker-04-04](https://cloud.githubusercontent.com/assets/7582849/7878878/560df8a8-05eb-11e5-9762-09a6a95739f6.png)

**Comment by bioshrimp** [comment]
hi @ApertoClaudi 
cool!
I can send ta vector file of the megaphone tonight when I am home. 
will an EPS file be fine?

**Comment by ApertoClaudi** [comment]
EPS will be awesome!!! :star: Can you make sure, that it's saved down to CS5? Thank you! :heart:

**Comment by bioshrimp** [comment]
I will! :)

**Comment by alicetragedy** [comment]
@ApertoClaudi yes, I agree that the whole thing would be too long! 
Sorry, by "on the website" I meant the one from the logo – Interstate and Interstate Black.
But Lato is ok too. :tada: 

The CMYK value for the stickers we have is (15, 100, 90, 10). This was only a tentative value, since I found no real CMYK values for the "Rails Girls Red" anywhere either, and it worked well with fine lines on white.
The other option is to use (19, 92, 100, 8) which is the red used in the logo. Maybe try both and see which you like best? At some point then we can define clear rules on which values to use so we don't keep changing them all the time. (_such a mess_)

Thank you for your great work! :+1:

**Comment by ApertoClaudi** [comment]
@alicetragedy Ah! I see, I think of the RGSoC page, when it comes to "the website" :blush: It's maybe the newbie factor. ;) 
I thought, there is some rights trouble with the interstate, like @alexwllms mentioned, because it's not a free font. But it would be nice to use it in all the RG designs in the future, so that we have a consistent look for everything. Hm! … 
Thank you for the CMYK values, I will check and use them! :)

Maybe we can make a little style guide next year, after the relaunch, as @anikalindtner mentioned. That would be perfect for all upcoming designs then. :+1:

**Comment by bioshrimp** [comment]
@ApertoClaudi  you can pull the megaphone EPS from my dropbox: 
https://www.dropbox.com/s/g1dw5ssbazjg5s1/megaphone-01.eps?dl=0
lemme know if you need anything else.

**Comment by sareg0** [comment]
We could also collect these thoughts on the fonts, colors etc, in our... 'style guide'. It's pretty bare, but we could gradually build this up, as we go along, and discover these things. I ALWAYS forget what the font face is that we use

**Comment by ApertoClaudi** [comment]
@bioshrimp Muchas gracias! :)

**Comment by anikalindtner** [comment]
@ApertoClaudi thanks so much for the sticker layouts <3 

I love the megaphone, too because it's so creative and puts together two design elements we've had around for a while, great job! 

Also OMG the little red hearts, I so want them.

I was wondering if we could make this one a bit smaller:
![rgsoc-sticker-02](https://cloud.githubusercontent.com/assets/7582849/7870301/a0bb0e76-0588-11e5-8afd-5e1733ccdaff.png)

Pull the heart a bit closer to the font and cut off the sticker sooner, so that it's a bit shorter and narrow? Something more like this:
![screen shot 2015-06-02 at 14 19 22](https://cloud.githubusercontent.com/assets/1711357/7935595/6ea85008-0932-11e5-8bbd-2ebfbbc2e375.png)

 wdyt?

And the one with RGSoC in the middle: I love the idea! Maybe we can try to make the outlines white and the fill red, so that the font can be white, since we have this on the Website in white as well? Just to try out if that also would look like?

**Comment by ApertoClaudi** [comment]
Dear sticker fan base, here are the new versions:

![rgsoc-sticker-mockup](https://cloud.githubusercontent.com/assets/7582849/8167740/95ac5fdc-13a0-11e5-8fe6-3bc6caed0192.jpg)

![rgsoc-sticker-soc_v2](https://cloud.githubusercontent.com/assets/7582849/8167752/a18aeee0-13a0-11e5-9fc3-df356ab06202.jpg)

![rgsoc-sticker-heart-rgsoc](https://cloud.githubusercontent.com/assets/7582849/8167755/a18eccd6-13a0-11e5-83db-4fc2b2ecd956.png)

![rgsoc-sticker-hearts](https://cloud.githubusercontent.com/assets/7582849/8167753/a18de6cc-13a0-11e5-926d-9b88d511d1b8.png)

![rgsoc-sticker-megaphone](https://cloud.githubusercontent.com/assets/7582849/8167754/a18eda1e-13a0-11e5-9a50-83613fe4daa2.png)

Thanks to @alicetragedy they have a bright new red, which is really pritty for those printed products, I think. :sparkles: 

If you're okay with these suggestions, I will make the documents ready for print and will give them to @sareg0 ?!

**Comment by alicetragedy** [comment]
sooooo pretty @ApertoClaudi! :heart_eyes_cat:

**Comment by sareg0** [comment]
heyyy!! I loves them! 

I have a few thoughts, and thank you so much for your hard work @ApertoClaudi!!
- from the selection above I am inclined to take 1, 3, and 4
- could you please put a round border on no.4 to make it clear for our sticker printer where to cut?
- could we somehow integrate the year number? Since these particular stickers are going to be commemorative for this year of students.

**Comment by ApertoClaudi** [comment]
Heyyyy, thanks for your kind words and your feedback. :blush: I now made the PDF files for sickermule and will upload it in the Slack Channel (because I don't know how to upload the to this site:https://github.com/rails-girls-summer-of-code/design/tree/master/stickers ... ).

**Comment by sareg0** [comment]
The stickers have been ordered so I am going to close this issue now
